### ISSUE TITLE
Crash in touch.py

### ISSUE THREAD

**Issue by p8mty** [pimoroni/presto#27]
Occasionally (2 or 3 times a day) my program crashes with the following:

```
>>> %Run -c $EDITOR_CONTENT

MPY: soft reboot
malloc self
set fb pointers
m_new_class(ST7701...
launch core1
launched core1
core1 returned

[[[[ Program output ]]]]

Traceback (most recent call last):
  File "<stdin>", line 265, in <module>
  File "touch.py", line 66, in poll
  File "touch.py", line 77, in _handle_touch
OSError: [Errno 5] EIO
```

The call in line 265 in my program is merely a call to touch.poll().
The line 77 in _handle_touch is dealing with i2c - I have no additional i2c devices attached to the Presto

It's not reproducible in that I don't know what to do to cause it, but if I poke at the screen for long enough, it will happen!

**Comment by MichaelBell** [comment]
I saw a crash a couple of times when running for a long time, which I suspect was this (but I wasn't running through Thonny so didn't see the stack).  We should probably just ignore the failure and wait for the next poll - I2C can be a bit unreliable at times.

**Comment by Gadgetoid** [comment]
Yup swallow the error and hope the next poll works 😬 with maybe a more permanent failure for multiple sequential errors?
